# This is a basic workflow to help you get started with Actions

name: .NET CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ,Beta ]
  pull_request:
    branches: [ main ,Beta ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build AmazooApp
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          
      - name: Restore App
        run: dotnet build AmazooApp/AmazooApp.sln
        
      - name: Build App
        run: dotnet build AmazooApp/AmazooApp/AmazooApp.csproj --configuration Release --no-restore
    
  # Build and run unit tests for CI    
#   unittests:
#     needs: build
#     name:  Run Tests
#     #the project will run on windows environment 
#     runs-on: windows-latest
#     steps: 
#     - uses: actions/checkout@v2
#     - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
#       uses: actions/setup-dotnet@v1.7.2
#       with:
#         dotnet-version: '6.0.x'
#     - name: Install dependencies
#       run: dotnet build AmazooApp/AmazooApp.sln
#     - name: Unit Tests
#       run: dotnet test AmazooApp/AmazooAppTest/AmazooAppTest.csproj --configuration Release --no-restore
